// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnmc2AdRPC-QSx7HeadzLtCXF_uSiszKk',
    appId: '1:592698331586:web:fac020127bc94c6c2d065b',
    messagingSenderId: '592698331586',
    projectId: 'memoji-46df6',
    authDomain: 'memoji-46df6.firebaseapp.com',
    storageBucket: 'memoji-46df6.appspot.com',
    measurementId: 'G-NJWWPEPK13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBczOw4WEzDhXvh1gkiCU0Hf2s9FfE2Ns',
    appId: '1:592698331586:android:4ba40266964021ca2d065b',
    messagingSenderId: '592698331586',
    projectId: 'memoji-46df6',
    storageBucket: 'memoji-46df6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyZF_lB1NWJFkAVBdw8tpHrtZL9tVt7A0',
    appId: '1:592698331586:ios:818671b3122e709b2d065b',
    messagingSenderId: '592698331586',
    projectId: 'memoji-46df6',
    storageBucket: 'memoji-46df6.appspot.com',
    iosClientId: '592698331586-nk3r0a4eeue02vj7cdd5mg7dnnvg5e7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyZF_lB1NWJFkAVBdw8tpHrtZL9tVt7A0',
    appId: '1:592698331586:ios:818671b3122e709b2d065b',
    messagingSenderId: '592698331586',
    projectId: 'memoji-46df6',
    storageBucket: 'memoji-46df6.appspot.com',
    iosClientId: '592698331586-nk3r0a4eeue02vj7cdd5mg7dnnvg5e7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );
}
